#!/usr/bin/env node
/**
 * augment-500mb.mjs — self-augmentation runner for the 500 MB Bonsai-4B-Q1_0 model.
 *
 * Reads data/project-tokens.json, selects the repo's highest-weight source files,
 * streams their content to the local 500 MB model at 127.0.0.1:6465 (OpenAI-compatible
 * /completion endpoint), and writes:
 *   - output/augmentation-output.ts  (real, compilable TS capturing generated patterns)
 *   - output/augmentation.metrics.json
 *   - output/augmentation.log
 *
 * So the improvement can be verified by concrete numbers.
 *
 * The 500 MB model (Bonsai-4B-Q1_0) is a true ternary Q1_0 GGUF served by llama-server.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(fileURLToPath(import.meta.url)); // scripts dir
const PROJECT_TOKENS = path.join(ROOT, "..", "data", "project-tokens.json");
const LLAMA_URL = "http://127.0.0.1:6465";
const MODEL_ID = "bonsai-4b";
const OUTPUT_DIR = path.join(ROOT, "output");
const LOG_FILE = path.join(OUTPUT_DIR, "augmentation.log");
const METRICS_FILE = path.join(OUTPUT_DIR, "augmentation.metrics.json");
const OUTPUT_CODE_FILE = path.join(OUTPUT_DIR, "augmentation-output.ts");

// Cap so the run is bounded and reproducible.
// MAX_BLOCKS can be overridden via the environment (e.g. MAX_BLOCKS=3 for a
// quick smoke test) to bound runtime without editing this file.
const MAX_PATTERNS = 20;      // max highest-weight source files to sample
const MAX_BLOCKS = Number(process.env.MAX_BLOCKS || 0); // 0 = unlimited
const BATCH_SIZE = 2048;      // chars per completion call
const MAX_OUTPUT_TOKENS = 128;

/** POST JSON to the local model server (OpenAI-compatible /completion). */
async function postCompletion(prompt, { temperature = 0.2, topP = 0.9, maxTokens = MAX_OUTPUT_TOKENS } = {}) {
  const res = await fetch(`${LLAMA_URL}/completion`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      prompt,
      temperature,
      top_p: topP,
      n_predict: maxTokens,
      stream: false,
    }),
  });
  if (!res.ok) {
    throw new Error(`model server returned HTTP ${res.status}: ${await res.text()}`);
  }
  const data = await res.json();
  return (data && data.content) || "";
}

/** Read the token pattern file (object schema with a `files` array). */
function readTokenPatterns() {
  const raw = fs.readFileSync(PROJECT_TOKENS, "utf8");
  const parsed = JSON.parse(raw);
  if (!parsed || !Array.isArray(parsed.files)) {
    throw new Error("project-tokens.json must be an object with a `files` array");
  }
  // Normalise to a plain map: repo-relative path -> token count.
  const out = {};
  for (const entry of parsed.files) {
    if (entry && typeof entry.path === "string" && typeof entry.tokens === "number") {
      out[entry.path] = entry.tokens;
    }
  }
  return out;
}

/** Escape a string for safe inclusion inside a TS double-quoted string literal. */
function tsEscape(s) {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t");
}

/** Write the generated patterns as a real, compilable TS module. */
function writeOutputCode(lines, generated) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  const escaped = lines.map((l) => `  "${tsEscape(l)}",`).join("\n");
  const escapedGen = generated.map((l) => `  "${tsEscape(l)}",`).join("\n");
  const tsContent = `/**
 * Augmentation output — generated by augment-500mb.mjs
 * Pattern sequences learned from the repo's project token patterns.
 *
 * Generated on: ${new Date().toISOString()}
 * Model: 500 MB Bonsai-4B-Q1_0 (true ternary Q1_0 GGUF)
 */

/** Source file paths sampled from data/project-tokens.json. */
export const sampledSourceFiles: string[] = [
${escaped}
];

/** Text generated by the 500 MB model given the sampled repo patterns. */
export const modelGeneratedText: string[] = [
${escapedGen}
];

/** Metadata so verification has concrete numbers to check. */
export const augmentationMetadata = {
  generatedAt: new Date().toISOString(),
  modelId: "${MODEL_ID}",
  modelSize: "500 MB",
  modelType: "true ternary Q1_0 GGUF",
  sampledFiles: ${lines.length},
  generatedBlocks: ${generated.length},
};
`;
  fs.writeFileSync(OUTPUT_CODE_FILE, tsContent);
  return tsContent;
}

/** Main workflow. */
async function run() {
  console.log("=== Augmentation Runner: 500 MB Bonsai-4B-Q1_0 ===");
  console.log(`LLM endpoint: ${LLAMA_URL}`);
  console.log(`Model: 500 MB Bonsai-4B-Q1_0 (true ternary, local)\n`);

  // 1) Read token patterns.
  console.log("[1/4] Reading project token patterns...");
  const tokenPatterns = readTokenPatterns();
  const entries = Object.entries(tokenPatterns);
  console.log(`Loaded ${entries.length} pattern entries.`);

  // 2) Pick highest-weight files that actually exist in the repo.
  console.log("\n[2/4] Selecting highest-weight existing source files...");
  const sampled = entries
    .sort((a, b) => b[1] - a[1])
    .slice(0, MAX_PATTERNS)
    .filter(([relPath]) => {
      const abs = path.resolve(ROOT, "..", relPath);
      if (!fs.existsSync(abs) || !fs.statSync(abs).isFile()) return false;
      // Skip lockfiles / generated noise — they add no useful augmentation signal.
      if (/package-lock\.json$|yarn\.lock$|pnpm-lock\.yaml$|\.map$|dist[\\/]/.test(relPath)) return false;
      // Only include text-ish sources.
      return /\.(ts|tsx|js|mjs|jsx|css|md|json|sh|py|rs|go|yml|yaml|html)$/.test(relPath);
    });

  const sourceFiles = [];
  const textBlocks = [];
  for (const [relPath] of sampled) {
    const abs = path.resolve(ROOT, "..", relPath);
    const content = fs.readFileSync(abs, "utf8").trim();
    if (!content) continue;
    sourceFiles.push(relPath);
    // Chunk larger files so each completion call gets a bounded prompt.
    for (let i = 0; i < content.length; i += BATCH_SIZE) {
      textBlocks.push(content.slice(i, i + BATCH_SIZE));
    }
  }
  console.log(`Sampled ${sourceFiles.length} files -> ${textBlocks.length} text blocks.`);

  // 3) Stream blocks to the 500 MB model and collect generations.
  console.log("\n[3/4] Augmenting with 500 MB model (streaming to " + LLAMA_URL + ")...");
  const generated = [];
  const blockLimit = MAX_BLOCKS > 0 ? Math.min(MAX_BLOCKS, textBlocks.length) : textBlocks.length;
  for (let i = 0; i < blockLimit; i++) {
    const block = textBlocks[i];
    try {
      const out = await postCompletion(block, { temperature: 0.2, maxTokens: MAX_OUTPUT_TOKENS });
      if (out && typeof out === "string") {
        generated.push(out.trim());
      }
    } catch (e) {
      console.warn(`  batch ${i + 1}/${textBlocks.length} failed: ${e.message}`);
    }
    if (i % 5 === 0) {
      console.log(`  batch ${i + 1}/${textBlocks.length}`);
    }
  }
  console.log(`Generated ${generated.length} text blocks from the model.`);

  // 4) Write outputs.
  console.log("\n[4/4] Writing augmentation outputs...");
  writeOutputCode(sourceFiles, generated);

  const metrics = {
    modelId: MODEL_ID,
    modelSize: "500 MB",
    modelType: "true ternary Q1_0 GGUF",
    llamaUrl: LLAMA_URL,
    patternsProcessed: sampled.length,
    sourceFiles,
    textBlocksProcessed: blockLimit,
    generatedBlocks: generated.length,
    outputFile: OUTPUT_CODE_FILE,
    metricsFile: METRICS_FILE,
    logFile: LOG_FILE,
    generatedAt: new Date().toISOString(),
  };
  fs.writeFileSync(METRICS_FILE, JSON.stringify(metrics, null, 2));

  const logLines = [
    "=== Augmentation Log ===",
    `Model: 500 MB Bonsai-4B-Q1_0 (true ternary Q1_0 GGUF)`,
    `LLM endpoint: ${LLAMA_URL}`,
    `Patterns loaded: ${entries.length}`,
    `Patterns sampled: ${sampled.length}`,
    `Text blocks streamed: ${blockLimit}`,
    `Generations captured: ${generated.length}`,
    "",
    "--- Sampled source files ---",
    ...sourceFiles,
    "",
    "--- Model-generated text (first 50) ---",
    ...generated.slice(0, 50).map((g) => `• ${g.substring(0, 200)}`),
    "",
    `--- Output written to: ${OUTPUT_CODE_FILE} ---`,
    `--- Metrics written to: ${METRICS_FILE} ---`,
    "=== End of Log ===",
  ];
  fs.writeFileSync(LOG_FILE, logLines.join("\n"));

  console.log("\n=== Augmentation Complete ===");
  console.log(`Verification: check ${LOG_FILE}, ${METRICS_FILE}, ${OUTPUT_CODE_FILE}`);
}

run().catch((e) => {
  console.error("Augmentation failed:", e);
  process.exit(1);
});
